'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { AppChatbot as AppChatbotElement, defineCustomElement as defineAppChatbot } from "chatbot-ui/dist/components/app-chatbot.js";
import React from 'react';

export type AppChatbotEvents = NonNullable<unknown>;

export const AppChatbot: StencilReactComponent<AppChatbotElement, AppChatbotEvents> = /*@__PURE__*/ createComponent<AppChatbotElement, AppChatbotEvents>({
    tagName: 'app-chatbot',
    elementClass: AppChatbotElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as AppChatbotEvents,
    defineCustomElement: defineAppChatbot
});
